This document analyzes the dataset logged by CARLA's system. The metrics to be measured are the following: 
1. **Reaction Time**
    - This is from the time the alert was sent until the time the driver made an action. This will help the researches know the appropriate time to give an alert. 
2. **Completion Time**
    - This measures the duration of the whole violation. From the alert being triggered until the speeding gets resolved. 
3. **Ignored Alert** 
    - This checks whether the driver made an action to the alert or ignored it. This will be used to prove the effectiveness of providing an alert to decrease speed.
4. **Speed Change**
    - This checks the speed. 
5. **Alert Effectiveness**
    - This computes for the number of resolved speeding violations, where the rider either *reduced throttle* or *brakes* which is then divided by all violations. (resolved/all violations) 

*Note: An action made by the driver can be either a release of the throttle or pressing on the brakes.*

In [47]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv("cleaned_Sim.csv")

df.head()

,timestamp,phase,speed_kmh,event,details,speed_limit,violation_start,violation_end,violation_state,event_start,event_id
0,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
1,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
2,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
3,1.771924e+09,4,1.17,WS_SEND,"{""phase"": 4, ""speed"": 1.17, ""speed_limit"": 30,...",30.0,False,False,0,0,0
4,1.771924e+09,4,1.19,WS_SEND,"{""phase"": 4, ""speed"": 1.19, ""speed_limit"": 30,...",30.0,False,False,0,0,0

In [49]:
df.columns

Index(['timestamp', 'phase', 'speed_kmh', 'event', 'details', 'speed_limit',
       'violation_start', 'violation_end', 'violation_state', 'event_start',
       'event_id'],
      dtype='object')

In [50]:
df["event"].unique()

array(['WS_SEND', 'YELLOW_LIGHT_PASS', 'REACTION', 'SPEED_VIOLATION',
       'RED_LIGHT_VIOLATION', 'PHASE_STOP', 'HUD_CUE'], dtype=object)

In [59]:
df.loc[
    (df["event_id"]==5),
    ["speed_kmh", "speed_limit", "details", "event_id"]
]

,speed_kmh,speed_limit,details,event_id
13107,37.29,30.0,"{""phase"": 3, ""speed"": 37.29, ""speed_limit"": 30...",5
13108,37.51,30.0,"{""phase"": 3, ""speed"": 37.51, ""speed_limit"": 30...",5
13109,37.88,30.0,"{""phase"": 3, ""speed"": 37.88, ""speed_limit"": 30...",5
13110,37.88,30.0,"{""phase"": 3, ""speed"": 37.88, ""speed_limit"": 30...",5
13111,38.18,30.0,"{""phase"": 3, ""speed"": 38.18, ""speed_limit"": 30...",5
...,...,...,...,...
13176,37.75,30.0,"{""phase"": 3, ""speed"": 37.75, ""speed_limit"": 30...",5
13177,37.75,30.0,"{""phase"": 3, ""speed"": 37.75, ""speed_limit"": 30...",5
13178,37.75,30.0,"{""phase"": 3, ""speed"": 37.75, ""speed_limit"": 30...",5
13179,48.73,30.0,Speed 48.73 km/h > limit 30.00 km/h at Locatio...,5
13180,35.19,NaN,action=VIOLATION_RESOLVED|time=4.07s|reaction_...,5

In [60]:
df.loc[
    df["event_id"].isin([6]),
    ["event_start", "speed_kmh", "speed_limit", "details", "event_id"]
]

,event_start,speed_kmh,speed_limit,details,event_id
26274,1,37.69,30.0,"{""phase"": 2, ""speed"": 37.69, ""speed_limit"": 30...",6
26275,0,37.69,30.0,"{""phase"": 2, ""speed"": 37.69, ""speed_limit"": 30...",6
26276,0,37.69,30.0,"{""phase"": 2, ""speed"": 37.69, ""speed_limit"": 30...",6
26277,0,37.69,30.0,"{""phase"": 2, ""speed"": 37.69, ""speed_limit"": 30...",6
26278,0,38.19,30.0,"{""phase"": 2, ""speed"": 38.19, ""speed_limit"": 30...",6
26279,0,38.19,30.0,"{""phase"": 2, ""speed"": 38.19, ""speed_limit"": 30...",6
26280,0,38.28,30.0,"{""phase"": 2, ""speed"": 38.28, ""speed_limit"": 30...",6
26281,0,38.19,30.0,"{""phase"": 2, ""speed"": 38.19, ""speed_limit"": 30...",6
26282,0,38.19,30.0,"{""phase"": 2, ""speed"": 38.19, ""speed_limit"": 30...",6
26283,0,38.19,30.0,"{""phase"": 2, ""speed"": 38.19, ""speed_limit"": 30...",6
26284,0,37.94,30.0,"{""phase"": 2, ""speed"": 37.94, ""speed_limit"": 30...",6
26285,0,37.88,30.0,"{""phase"": 2, ""speed"": 37.88, ""speed_limit"": 30...",6
26286,0,37.88,30.0,"{""phase"": 2, ""speed"": 37.88, ""speed_limit"": 30...",6
26287,0,37.88,30.0,"{""phase"": 2, ""speed"": 37.88, ""speed_limit"": 30...",6
26288,0,37.52,30.0,"{""phase"": 2, ""speed"": 37.52, ""speed_limit"": 30...",6
26289,0,37.52,30.0,"{""phase"": 2, ""speed"": 37.52, ""speed_limit"": 30...",6
26290,0,37.01,30.0,"{""phase"": 2, ""speed"": 37.01, ""speed_limit"": 30...",6
26291,0,38.28,30.0,Speed 38.28 km/h > limit 30.00 km/h at Locatio...,6
26292,0,36.93,NaN,action=VIOLATION_RESOLVED|time=0.90s|reaction_...,6

In [ ]:
df.loc[df["speed_limit"] == 60, "event_id"].unique()

array([  4,   0,  17,  38, 111, 144, 164, 183, 184, 185, 186, 220, 282,
       292, 372])

## Metrics Computation & Analysis

In [ ]:
df_Metrics = df.copy()
df_Metrics

,timestamp,phase,speed_kmh,event,details,speed_limit,violation_start,violation_end,violation_state,event_start,event_id
0,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
1,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
2,1.771924e+09,4,0.71,WS_SEND,"{""phase"": 4, ""speed"": 0.71, ""speed_limit"": 30,...",30.0,False,False,0,0,0
3,1.771924e+09,4,1.17,WS_SEND,"{""phase"": 4, ""speed"": 1.17, ""speed_limit"": 30,...",30.0,False,False,0,0,0
4,1.771924e+09,4,1.19,WS_SEND,"{""phase"": 4, ""speed"": 1.19, ""speed_limit"": 30,...",30.0,False,False,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
446324,1.771682e+09,3,3.53,WS_SEND,"{""phase"": 3, ""speed"": 3.53, ""speed_limit"": 30,...",30.0,False,False,0,0,0
446325,1.771682e+09,3,3.53,WS_SEND,"{""phase"": 3, ""speed"": 3.53, ""speed_limit"": 30,...",30.0,False,False,0,0,0
446326,1.771682e+09,3,3.41,WS_SEND,"{""phase"": 3, ""speed"": 3.41, ""speed_limit"": 30,...",30.0,False,False,0,0,0
446327,1.771682e+09,3,674.87,PHASE_STOP,Assisted-H,NaN,False,False,0,0,0
446328,1.771682e+09,3,674.87,PHASE_STOP,Assisted-H,NaN,False,False,0,0,0

### Reaction Time

In [61]:
# look for details == "action=REDUCE_THROTTLE"
df_Metrics["slow_down"] = df_Metrics["details"].str.contains("REDUCE_THROTTLE", na=False)

*action=REDUCE_THROTTLE* is a signal that the driver released yung tapak niya sa pedal.

In [62]:
# get timestamp and event_id
event_start_time = df_Metrics[df_Metrics["event_start"] == 1].groupby("event_id")["timestamp"].first()

reaction_time = df_Metrics[df_Metrics["slow_down"]].groupby("event_id")["timestamp"].first()

In [63]:
reaction_timeK = reaction_time - event_start_time

In [64]:
display(reaction_timeK.head(20))

event_id
0      NaN
1     0.73
2     1.82
3     0.73
4      NaN
5      NaN
6      NaN
7     0.46
8      NaN
9     0.77
10    0.88
11     NaN
12    0.75
13    0.93
14    2.73
15    0.78
16     NaN
17     NaN
18     NaN
19    0.50
Name: timestamp, dtype: float64

In [ ]:
df_Metrics["alert_sent"] = (
    df_Metrics["event"].eq("WS_SEND") &
    df_Metrics["details"].str.contains('"overspeed": true', na=False)
)

In [ ]:
alert_time = df_Metrics[df_Metrics["alert_sent"]].groupby("event_id")["timestamp"].first()
reaction_timeG = reaction_time - alert_time

In [52]:
display(reaction_timeG.head(20))

event_id
0      NaN
1     0.73
2     1.82
3     0.73
4      NaN
5      NaN
6      NaN
7     0.46
8      NaN
9     0.77
10    0.88
11     NaN
12    0.75
13    0.93
14    2.73
15    0.78
16     NaN
17     NaN
18     NaN
19    0.50
Name: timestamp, dtype: float64

*Note: in the cases of NaN values: at times the rider is just above the speeding threshold, the system in CARLA might not have detected enough throttle release. Therefore, in the subtracting the action to the start becomes not applicable.*

In [70]:
reaction_table = reaction_timeK.reset_index(name="reaction_time")

### Ignored Alert

In [68]:
ignored = (reaction_timeK >= 2.5).astype(int)

event_id
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    1
Name: timestamp, dtype: int64

In [73]:
reaction_table["ignored"] = (
    (reaction_table["reaction_time"] >= 2.5)
).astype(int)

In [75]:
display(reaction_table.head(15))

    event_id  reaction_time  ignored
0          0            NaN        0
1          1           0.73        0
2          2           1.82        0
3          3           0.73        0
4          4            NaN        0
5          5            NaN        0
6          6            NaN        0
7          7           0.46        0
8          8            NaN        0
9          9           0.77        0
10        10           0.88        0
11        11            NaN        0
12        12           0.75        0
13        13           0.93        0
14        14           2.73        1

### Speed Change

### Braking Distance

## Alert-Phase Analysis

In [ ]:
# Transfer to Sim Analysis

#Baseline
df_NC = df[df['phase'] == 1]
display(df_NC)

# Audio Only 
df_AO = df[df['phase'] == 2]
#display(df_AO)

# Haptic Only
df_HO = df[df['phase'] == 3]
#display(df_HO)

# Combination Haptic and Audio
df_HA = df[df['phase'] == 4]
#display(df_HA)

,timestamp,phase,speed_kmh,event,details,speed_limit,Location_X,Location_Y,violation_flag,event_id
7122,1.771924e+09,1,37.14,REACTION,action=REDUCE_THROTTLE|time=0.21s|control={'th...,NaN,NaN,NaN,0,0
7123,1.771924e+09,1,37.14,SPEED_VIOLATION,Speed 37.14 km/h > limit 30.00 km/h at Locatio...,30.0,-85.912148,35.437183,1,4
7124,1.771924e+09,1,36.53,REACTION,action=VIOLATION_RESOLVED|time=0.26s|reaction_...,NaN,NaN,NaN,-1,0
7125,1.771924e+09,1,14.79,YELLOW_LIGHT_PASS,"Passed yellow at Location(x=-85.075447, y=113....",NaN,-85.075447,113.654617,0,0
7126,1.771924e+09,1,19.89,RED_LIGHT_VIOLATION,TrafficLight Violation at Location(x=-22.61465...,NaN,-22.614655,136.981354,0,0
...,...,...,...,...,...,...,...,...,...,...
437869,1.771680e+09,1,36.00,REACTION,action=VIOLATION_RESOLVED|time=1.78s|reaction_...,NaN,NaN,NaN,-1,0
437870,1.771680e+09,1,37.01,SPEED_VIOLATION,Speed 37.01 km/h > limit 30.00 km/h at Locatio...,30.0,-142.610382,118.224449,1,887
437871,1.771680e+09,1,36.70,REACTION,action=VIOLATION_RESOLVED|time=0.15s|reaction_...,NaN,NaN,NaN,-1,0
437872,1.771680e+09,1,475.51,PHASE_STOP,Baseline,NaN,NaN,NaN,0,0
437873,1.771680e+09,1,475.51,PHASE_STOP,Baseline,NaN,NaN,NaN,0,0

In [ ]:
#speeding_count = df["overspeed"].sum()
#VIOLATION COUNTS
speeding_count = df[df["event"] == "SPEED_VIOLATION"].shape[0]
stoplight_countRed = df[df["event"] == "RED_LIGHT_VIOLATION"].shape[0]
stoplight_countYellow = df[df["event"] == "YELLOW_LIGHT_PASS"].shape[0]
print("Speed count: ", speeding_count)
print("Red Light count: ", stoplight_countRed)
print("Yellow Light count: ", stoplight_countYellow)

Speed count:  926
Red Light count:  44033
Yellow Light count:  91