## Data Cleaning and Preparation
What does this dataset do 
- this notebook cleans the data and creates a csv file that will be ready for: 

a. NASA-TLX data analysis 
- This will be the document analyzing the perceived workload of tasks done. 
    
b. Simulation data analysis
- This will be the document analyzing the statistics and the actions done by the participants during the simulation.

Important note: 
csv files for nasa-tlx should be in 1 folder and csv files for simulation should be in a separate folder

#### Data Description

### Simulation 
| Column Name        | Description                                                  |
|--------------------|--------------------------------------------------------------|
| **timestamp** | recorded time when an occurence occured |
| **phase** | classification of drive |
| **scenario** | Type of occurence that happened|
| **speed_kmh** | recorded speed the participant was going |
| **event** | the violation or occurence type |
| **details** | Split into Violation and Location |
| **Violation** | Specific Violation acquired (?) | 
| **Location** | Exact coordinates the violation occured. This differs every time. |

### NASA TLX 
| Column Name        | Description                                                  |
|--------------------|--------------------------------------------------------------|
| **Participant**   | Participant number for tracking, acts as a unique identifier of a participant |
| **Task Name** | Type of alerts that the participant took (Baseline, AO - Audio Only, HO - Haptic Only, AH - Audio and Haptic) |
| **Mental Demand**| Mental and perceptual activity |
| **Physical Demand**| Physical activity required | 
| **Temporal Demand** | Time pressure according to the pace |
| **Performance** | Successfulness in completing the task |
| **Effort** | 
| **Frustration**| |

#### Data Collection & Methodology 
**NASATLX**
This dataset came from the NASATLX site. The participants were asked to answer the same exact questions. This was done every after drive to gauge their experience immediately after the drive. Upon completing the whole 4 drives, the csv file was generated. 

**Simulation**
This dataset came from the log tracker of the CARLA application, which records the corresponding type of drive and the violations committed. When a violation was done, the coordinates,

#### Biases and Limitations

#### Sources and Credits
NASA-TLX site: https://nasa-tlx-calculator.vercel.app/

**Reminders**
- make sure there are 2 separate folders > 1 each for the respective data (1 csv folder for Sim, 1 csv folder for NASATLX)

### Preprocessing

In [41]:
import pandas as pd
import numpy as np
import glob

In [42]:
files = glob.glob("/Users/karencafe/Desktop/ThesisTest/SIMCSV/*.csv")

df_simulation = pd.concat(
    (pd.read_csv(f) for f in files),
    ignore_index=True
)

display(df_simulation)

,timestamp,phase,scenario,speed_kmh,event,details
0,1.770437e+09,1,START,0.00,PHASE_START,Baseline
1,1.770437e+09,1,HUD,0.56,HUD_CUE,Turn Right at the First Exit
2,1.770437e+09,1,HUD,0.90,HUD_CUE,Turn Right at the First Exit
3,1.770437e+09,1,HUD,1.06,HUD_CUE,Turn Right at the First Exit
4,1.770437e+09,1,HUD,1.13,HUD_CUE,Turn Right at the First Exit
...,...,...,...,...,...,...
21762,1.770439e+09,4,HUD,0.01,HUD_CUE,Turn Right at the First Exit
21763,1.770439e+09,4,HUD,0.01,HUD_CUE,Turn Right at the First Exit
21764,1.770439e+09,4,HUD,0.01,HUD_CUE,Turn Right at the First Exit
21765,1.770439e+09,4,STOP,318.76,PHASE_STOP,Assisted-AH
21766,1.770439e+09,4,STOP,318.76,PHASE_STOP,Assisted-AH

In [43]:
# Convert to datetime (if not already)
df_simulation["timestamp"] = pd.to_datetime(df_simulation["timestamp"], unit="s")

# Compute elapsed time in seconds from first event
df_simulation["elapsed_seconds"] = (
    df_simulation["timestamp"] - df_simulation["timestamp"].iloc[0]
).dt.total_seconds()

print(df_simulation)

                          timestamp  phase scenario  speed_kmh        event  \
0     2026-02-07 03:55:12.079999924      1    START       0.00  PHASE_START
1     2026-02-07 03:55:25.660000086      1      HUD       0.56      HUD_CUE
2     2026-02-07 03:55:25.710000038      1      HUD       0.90      HUD_CUE
3     2026-02-07 03:55:25.769999981      1      HUD       1.06      HUD_CUE
4     2026-02-07 03:55:25.829999924      1      HUD       1.13      HUD_CUE
...                             ...    ...      ...        ...          ...
21762 2026-02-07 04:32:41.849999905      4      HUD       0.01      HUD_CUE
21763 2026-02-07 04:32:41.980000019      4      HUD       0.01      HUD_CUE
21764 2026-02-07 04:32:42.089999914      4      HUD       0.01      HUD_CUE
21765 2026-02-07 04:32:42.089999914      4     STOP     318.76   PHASE_STOP
21766 2026-02-07 04:32:42.089999914      4     STOP     318.76   PHASE_STOP

                            details  elapsed_seconds
0                          Baseline             0.00
1      Turn Right at the First Exit            13.58
2      Turn Right at the First Exit            13.63
3      Turn Right at the First Exit            13.69
4      Turn Right at the First Exit            13.75
...                             ...              ...
21762  Turn Right at the First Exit          2249.77
21763  Turn Right at the First Exit          2249.90
21764  Turn Right at the First Exit          2250.01
21765                   Assisted-AH          2250.01
21766                   Assisted-AH          2250.01

[21767 rows x 7 columns]

In [44]:
# If timestamp is already datetime
df_simulation["timestamp"] = (
    df_simulation["timestamp"] - df_simulation["timestamp"].iloc[0]
).dt.total_seconds()

print(df_simulation)

       timestamp  phase scenario  speed_kmh        event  \
0           0.00      1    START       0.00  PHASE_START
1          13.58      1      HUD       0.56      HUD_CUE
2          13.63      1      HUD       0.90      HUD_CUE
3          13.69      1      HUD       1.06      HUD_CUE
4          13.75      1      HUD       1.13      HUD_CUE
...          ...    ...      ...        ...          ...
21762    2249.77      4      HUD       0.01      HUD_CUE
21763    2249.90      4      HUD       0.01      HUD_CUE
21764    2250.01      4      HUD       0.01      HUD_CUE
21765    2250.01      4     STOP     318.76   PHASE_STOP
21766    2250.01      4     STOP     318.76   PHASE_STOP

                            details  elapsed_seconds
0                          Baseline             0.00
1      Turn Right at the First Exit            13.58
2      Turn Right at the First Exit            13.63
3      Turn Right at the First Exit            13.69
4      Turn Right at the First Exit            13.75
...                             ...              ...
21762  Turn Right at the First Exit          2249.77
21763  Turn Right at the First Exit          2249.90
21764  Turn Right at the First Exit          2250.01
21765                   Assisted-AH          2250.01
21766                   Assisted-AH          2250.01

[21767 rows x 7 columns]

In [45]:
df_simulation["datetime"] = pd.to_datetime(df_simulation["timestamp"], unit="s")
df_simulation["seconds_only"] = df_simulation["datetime"].dt.second

print(df_simulation)

       timestamp  phase scenario  speed_kmh        event  \
0           0.00      1    START       0.00  PHASE_START
1          13.58      1      HUD       0.56      HUD_CUE
2          13.63      1      HUD       0.90      HUD_CUE
3          13.69      1      HUD       1.06      HUD_CUE
4          13.75      1      HUD       1.13      HUD_CUE
...          ...    ...      ...        ...          ...
21762    2249.77      4      HUD       0.01      HUD_CUE
21763    2249.90      4      HUD       0.01      HUD_CUE
21764    2250.01      4      HUD       0.01      HUD_CUE
21765    2250.01      4     STOP     318.76   PHASE_STOP
21766    2250.01      4     STOP     318.76   PHASE_STOP

                            details  elapsed_seconds  \
0                          Baseline             0.00
1      Turn Right at the First Exit            13.58
2      Turn Right at the First Exit            13.63
3      Turn Right at the First Exit            13.69
4      Turn Right at the First Exit            13.75
...                             ...              ...
21762  Turn Right at the First Exit          2249.77
21763  Turn Right at the First Exit          2249.90
21764  Turn Right at the First Exit          2250.01
21765                   Assisted-AH          2250.01
21766                   Assisted-AH          2250.01

                           datetime  seconds_only
0     1970-01-01 00:00:00.000000000             0
1     1970-01-01 00:00:13.580000162            13
2     1970-01-01 00:00:13.630000114            13
3     1970-01-01 00:00:13.690000057            13
4     1970-01-01 00:00:13.750000000            13
...                             ...           ...
21762 1970-01-01 00:37:29.769999981            29
21763 1970-01-01 00:37:29.900000095            29
21764 1970-01-01 00:37:30.009999990            30
21765 1970-01-01 00:37:30.009999990            30
21766 1970-01-01 00:37:30.009999990            30

[21767 rows x 9 columns]

In [46]:
#remove rows
df_simulation = df_simulation[df_simulation['event'] != 'HUD_CUE']

# Scenario is redundant 
df_simulation = df_simulation.drop(columns=["scenario"]) 

# Split details into 2 columns, 1 for the type of violation, 1 for the coordinates it happened 
split_cols = df_simulation['details'].str.split('at Location', n=1, expand=True)

df_simulation['Violation'] = split_cols[0]
df_simulation['Coordinates'] = split_cols[1]

# Drop the details column

df_simulation = df_simulation.drop(columns=["details"])

# Display 
display(df_simulation)

,timestamp,phase,speed_kmh,event,elapsed_seconds,datetime,seconds_only,Violation,Coordinates
0,0.00,1,0.00,PHASE_START,0.00,1970-01-01 00:00:00.000000000,0,Baseline,None
413,46.44,1,20.46,RED_LIGHT_VIOLATION,46.44,1970-01-01 00:00:46.440000057,46,TrafficLight Violation,"(x=-58.396709, y=-1.977270, z=0.001787)"
710,68.92,1,42.72,SPEED_VIOLATION,68.92,1970-01-01 00:01:08.920000076,8,Speed 42.72 km/h > limit 30.00 km/h,"(x=-86.167862, y=68.519760, z=0.833062)"
754,72.11,1,20.53,YELLOW_LIGHT_PASS,72.11,1970-01-01 00:01:12.110000133,12,Passed yellow,"(x=-86.318329, y=113.893402, z=0.147602)"
921,82.49,1,25.65,RED_LIGHT_VIOLATION,82.49,1970-01-01 00:01:22.490000009,22,TrafficLight Violation,"(x=-22.873449, y=135.096573, z=0.001772)"
...,...,...,...,...,...,...,...,...,...
21453,2228.01,4,68.36,SPEED_VIOLATION,2228.01,1970-01-01 00:37:08.009999990,8,Speed 68.36 km/h > limit 60.00 km/h,"(x=36.700344, y=-138.796722, z=2.028577)"
21487,2230.31,4,56.30,RED_LIGHT_VIOLATION,2230.31,1970-01-01 00:37:10.310000181,10,TrafficLight Violation,"(x=5.175562, y=-122.113327, z=0.001643)"
21537,2233.61,4,91.12,SPEED_VIOLATION,2233.61,1970-01-01 00:37:13.610000133,13,Speed 91.12 km/h > limit 60.00 km/h,"(x=0.831588, y=-109.375839, z=0.001519)"
21765,2250.01,4,318.76,PHASE_STOP,2250.01,1970-01-01 00:37:30.009999990,30,Assisted-AH,None
21766,2250.01,4,318.76,PHASE_STOP,2250.01,1970-01-01 00:37:30.009999990,30,Assisted-AH,None

In [47]:
df_simulation.columns

Index(['timestamp', 'phase', 'speed_kmh', 'event', 'elapsed_seconds',
       'datetime', 'seconds_only', 'Violation', 'Coordinates'],
      dtype='object')

In [48]:
print(df_simulation['event'].unique())

['PHASE_START' 'RED_LIGHT_VIOLATION' 'SPEED_VIOLATION' 'YELLOW_LIGHT_PASS'
 'PHASE_STOP']

In [49]:
display(df_simulation.columns)

Index(['timestamp', 'phase', 'speed_kmh', 'event', 'elapsed_seconds',
       'datetime', 'seconds_only', 'Violation', 'Coordinates'],
      dtype='object')

In [50]:
#df["speed"] = pd.to_numeric(df["speed"], errors="coerce")
#df["speed_limit"] = pd.to_numeric(df["speed_limit"], errors="coerce")

In [51]:
df_simulation.to_csv("cleaned_Sim.csv", index=False)

# NASA TLX CLEANING

In [58]:
files = glob.glob("/Users/karencafe/Desktop/ThesisTest/NASACSV/*.csv")
# change to the path of the NASATLX folder containing all the csv files

df2 = pd.concat(
    (pd.read_csv(f) for f in files),
    ignore_index=True
)

display(df2)

,Participant,Task Id,Task Name,Mental Demand,Physical Demand,Temporal Demand,Performance,Effort,Frustration,Raw Score,MD Weight,PD Weight,TD Weight,PF Weight,EF Weight,FR Weight,Weighted Score
0,8,1,AH,70,60,40,70,60,80,63.333333,-1,-1,-1,-1,-1,-1,-1
1,8,2,NC,80,70,70,70,70,70,71.666667,-1,-1,-1,-1,-1,-1,-1
2,8,3,AO,80,70,70,70,70,70,71.666667,-1,-1,-1,-1,-1,-1,-1
3,8,4,HO,80,70,70,70,70,70,71.666667,-1,-1,-1,-1,-1,-1,-1
4,9,1,NC,20,40,40,60,60,40,43.333333,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,11,5,NC,5,15,5,65,50,0,23.333333,-1,-1,-1,-1,-1,-1,-1
68,5,1,AH,80,80,60,20,20,20,46.666667,-1,-1,-1,-1,-1,-1,-1
69,5,2,NC,80,80,60,10,10,10,41.666667,-1,-1,-1,-1,-1,-1,-1
70,5,3,HO,90,90,70,20,20,20,51.666667,-1,-1,-1,-1,-1,-1,-1
71,5,4,AO,80,80,80,10,10,10,45.000000,-1,-1,-1,-1,-1,-1,-1

In [59]:
df2 = df2.drop(columns=["Task Id", "MD Weight", "PD Weight", "TD Weight", "PF Weight", "EF Weight", "FR Weight", "Weighted Score"])

display(df2)

,Participant,Task Name,Mental Demand,Physical Demand,Temporal Demand,Performance,Effort,Frustration,Raw Score
0,8,AH,70,60,40,70,60,80,63.333333
1,8,NC,80,70,70,70,70,70,71.666667
2,8,AO,80,70,70,70,70,70,71.666667
3,8,HO,80,70,70,70,70,70,71.666667
4,9,NC,20,40,40,60,60,40,43.333333
...,...,...,...,...,...,...,...,...,...
67,11,NC,5,15,5,65,50,0,23.333333
68,5,AH,80,80,60,20,20,20,46.666667
69,5,NC,80,80,60,10,10,10,41.666667
70,5,HO,90,90,70,20,20,20,51.666667
71,5,AO,80,80,80,10,10,10,45.000000

In [60]:
df2["Raw Score"] = df2["Raw Score"].round(2)
display(df2.head(3))

,Participant,Task Name,Mental Demand,Physical Demand,Temporal Demand,Performance,Effort,Frustration,Raw Score
0,8,AH,70,60,40,70,60,80,63.33
1,8,NC,80,70,70,70,70,70,71.67
2,8,AO,80,70,70,70,70,70,71.67

In [61]:
# Makes sure no mislabeled Task Name
print(df2['Task Name'].unique())

['AH' 'NC' 'AO' 'HO']

Clean task name 
- NC = no cue / baseline 
- AO = Audio Only 
- HO = Haptic Only 
- AH = Audio and Haptic / both Combined

In [67]:
df2.to_csv("cleaned_NASATLX.csv", index=False)

In [68]:
pivot_all = df2.pivot_table(
    index="Participant",
    columns="Task Name",
    values=[
        "Mental Demand",
        "Physical Demand",
        "Temporal Demand",
        "Performance",
        "Effort",
        "Frustration",
        "Raw Score"
    ]
)

# Flatten multi-level columns
pivot_all.columns = [f"{dim}_{cond}" for dim, cond in pivot_all.columns]

pivot_all.reset_index(inplace=True)

pivot_all.to_csv("NASATLX_pivot_all.csv", index=False)

In [66]:
dimensions = [
    "Mental Demand",
    "Physical Demand",
    "Temporal Demand",
    "Performance",
    "Effort",
    "Frustration"
]

for dim in dimensions:
    pivot_dim = df2.pivot_table(
        index="Participant",
        columns="Task Name",
        values=dim
    )
    
    pivot_dim.reset_index(inplace=True)
    
    # Save file
    filename = dim.replace(" ", "_") + ".csv"
    pivot_dim.to_csv(filename, index=False)